/**
 * Hair-care brand names for the product form dropdown.
 * Sorted alphabetically, ignoring accents and punctuation.
 * Includes drugstore own-brands (Balea, Isana, Cien, Equate, Kruidvat, ...).
 * Not exhaustive — the field should still accept free text.
 */
export const HAIR_BRANDS = [
  "Act+Acre",
  "Acure",
  "Adwoa Beauty",
  "Africa's Best",
  "Afrocenchix",
  "Alberto Balsam",
  "Alfaparf Milano",
  "Alikay Naturals",
  "Alterna",
  "Alterra",
  "Alverde",
  "Amend",
  "Amika",
  "Amino Mason",
  "Amorepacific",
  "Andalou Naturals",
  "Anua",
  "Aphogee",
  "Apivita",
  "Apse",
  "Aquage",
  "Arata",
  "Arganmidas",
  "Arimino",
  "Aromatica",
  "As I Am",
  "Asience",
  "Attitude",
  "Aunt Jackie's",
  "Aussie",
  "Authentic Beauty Concept",
  "Avalon Organics",
  "Aveda",
  "Aveeno",
  "Aveo",
  "Avlon",
  "Ayur",
  "Balea",
  "Bare Anatomy",
  "Bask & Bloom",
  "Batiste",
  "Bed Head",
  "Bee & Flower",
  "Bielenda",
  "Bio Extratus",
  "Bioderma",
  "Biolage",
  "Biotique",
  "Blue Magic",
  "Bondi Boost",
  "Boots Botanics",
  "Botanist",
  "Bouclème",
  "Bounce Curl",
  "Braé",
  "Bread Beauty Supply",
  "Briogeo",
  "Brocato",
  "Bübchen",
  "Bumble and bumble",
  "Cadiveu",
  "Camille Rose",
  "Cantu",
  "Caprice",
  "Carol's Daughter",
  "Cattier",
  "Ceremonia",
  "Charles Worthington",
  "Charlotte Mensah",
  "CHI",
  "Christophe Robin",
  "Cien",
  "Clairol",
  "Clear",
  "Color Wow",
  "Coslys",
  "Creme of Nature",
  "Crown Affair",
  "Curl Junkie",
  "Curl Keeper",
  "Curls",
  "Curlsmith",
  "Cutrin",
  "CVS Health",
  "Dabur Amla",
  "Dalin",
  "Dark and Lovely",
  "Dashu",
  "Davines",
  "De Lorenzo",
  "Deliplus",
  "Denorex",
  "Desert Essence",
  "Design Essentials",
  "DevaCurl",
  "Diane Bonheur",
  "Dizziak",
  "Doo Gro",
  "Dr. Groot",
  "Dr. Hauschka",
  "Ducray",
  "Echosline",
  "Eden BodyWorks",
  "Elasta QP",
  "Elastine",
  "Eleven Australia",
  "Elidor",
  "Elkos",
  "Elseve",
  "Elvital",
  "Elvive",
  "Equate",
  "Etos",
  "Eudora",
  "Eufora",
  "Evo",
  "Faith in Nature",
  "Finesse",
  "Fino",
  "Flora & Curl",
  "Forest Essentials",
  "Four Reasons",
  "Framesi",
  "Fudge",
  "Function of Beauty",
  "Garnier Fructis",
  "Gatsby",
  "Giovanni",
  "Gisou",
  "Gliss",
  "Goldwell",
  "got2b",
  "Grafen",
  "Green Beaver",
  "Green People",
  "Griffus",
  "Grow Gorgeous",
  "Guhl",
  "Hairburst",
  "Hairstory",
  "Hask",
  "Haskell",
  "Hawaiian Silky",
  "Head & Shoulders",
  "Helen Seward",
  "HEMA",
  "Herbal Essences",
  "Herbal Glo",
  "Himalaya",
  "&honey",
  "Honeyque",
  "Hoyu",
  "Ichikami",
  "IGK",
  "Indulekha",
  "Infusium 23",
  "Innersense",
  "Innisfree",
  "Inoar",
  "Instituto Español",
  "Isana",
  "It's a 10",
  "Jamaican Mango & Lime",
  "Jane Carter Solution",
  "Jason",
  "Jessicurl",
  "Joanna",
  "John Frieda",
  "Joico",
  "Just Herbs",
  "K18",
  "Kaaral",
  "Kama Ayurveda",
  "Kao Essential",
  "K-Classic",
  "Kenra",
  "Keracare",
  "Kérastase",
  "Kerastase Japan",
  "Kerasys",
  "Keratin Complex",
  "Kesh King",
  "Kevin Murphy",
  "Khadi Natural",
  "Kinky-Curly",
  "Kirkland Signature",
  "Klorane",
  "KMS",
  "Kneipp",
  "Konzil",
  "Korres",
  "Kose",
  "Kracie",
  "Kruidvat",
  "Kundal",
  "La Roche-Posay",
  "Label.m",
  "Lacura",
  "Lador",
  "Lavera",
  "Le Petit Marseillais",
  "Lebel",
  "Lee Stafford",
  "Leonor Greyl",
  "LG Care",
  "Life Brand",
  "Live Clean",
  "Living Proof",
  "Logona",
  "Lola Cosmetics",
  "L'Oréal Paris",
  "L'Oréal Professionnel",
  "Lucido-L",
  "Lush",
  "Luster's",
  "Lux",
  "Mamaearth",
  "Mane 'n Tail",
  "Marc Anthony",
  "Marion",
  "Matrix",
  "Maui Moisture",
  "Melanin Haircare",
  "Melvita",
  "Merit",
  "Mielle Organics",
  "Milbon",
  "Mill Creek",
  "Mise en Scène",
  "Miss Jessie's",
  "Mizani",
  "Moist Diane",
  "Moremo",
  "Moroccanoil",
  "Motions",
  "Muk",
  "Muriel",
  "Nairobi",
  "Nak",
  "Napla",
  "Nard",
  "Natura",
  "Natura Siberica",
  "Naturalicious",
  "Nature Box",
  "Nature Republic",
  "Nature's Gate",
  "Neutrogena",
  "Nexxus",
  "Nioxin",
  "Nivea",
  "Nizoral",
  "Nook",
  "Not Your Mother's",
  "Noughty",
  "Novex",
  "Nyle",
  "Obia Naturals",
  "OGX",
  "Olaplex",
  "O&M Original & Mineral",
  "Ombia",
  "Optimum",
  "Organic Root Stimulator",
  "Oribe",
  "Ouai",
  "Ouidad",
  "Oyin Handmade",
  "Palmer's",
  "Palmolive",
  "Pantene",
  "Pantene Pro-V",
  "Parachute",
  "Patanjali",
  "Pattern Beauty",
  "Paul Mitchell",
  "Percy & Reed",
  "Pert Plus",
  "Philip Kingsley",
  "Phyto",
  "Pink",
  "Playa",
  "Prell",
  "Prose",
  "Pureology",
  "Pyunkang Yul",
  "Qhemet Biologics",
  "Queen Helene",
  "Rahua",
  "R+Co",
  "Redken",
  "Rejoice",
  "René Furterer",
  "Righteous Roots",
  "Rita Hazan",
  "Roux",
  "Rusk",
  "Ryeo",
  "Ryo",
  "Salerm",
  "Salon Line",
  "Salon Selectives",
  "Sante",
  "Savital",
  "Schauma",
  "Schwarzkopf",
  "Scruples",
  "Sebamed",
  "Sebastian",
  "Seda",
  "Sedal",
  "Segreta",
  "Seinz",
  "Selsun Blue",
  "Sexy Hair",
  "Shea Moisture",
  "Shea Radiance",
  "Shiseido",
  "Shockwaves",
  "Silk Elements",
  "Sim Sensitive",
  "Skala",
  "Sofn'free",
  "Soulflower",
  "Sta-Sof-Fro",
  "Suave",
  "Sukin",
  "Sunny Isle",
  "Sunsilk",
  "Superdrug",
  "Surface",
  "Syoss",
  "Taft",
  "Tahe",
  "Taliah Waajid",
  "Terra Naturi",
  "TGIN",
  "The Body Shop",
  "The Man Company",
  "Tigi Catwalk",
  "Timotei",
  "Toni & Guy",
  "Tresemmé",
  "Trichup",
  "Tropic Isle Living",
  "Truss",
  "Tsubaki",
  "Tsubaki Premium",
  "Ultra Doux",
  "Umberto Giannini",
  "Uncle Funky's Daughter",
  "Uno",
  "Up & Up",
  "Urtekram",
  "Valquer",
  "Vatika",
  "Vegamour",
  "Verb",
  "Vichy Dercos",
  "Vidal Sassoon",
  "Vidal Sassoon Japan",
  "Virtue",
  "VO5",
  "Vosene",
  "Weleda",
  "Wella",
  "White Rain",
  "Widi Care",
  "WOW Skin Science",
  "Yamá",
  "Yolu",
  "Yves Rocher",
  "Ziaja",
] as const;
