import type { Ingredient } from "@/types";

/**
 * Ingredients that are NOT compatible with the Curly Girl method, grouped by
 * `type`. Seeded from the original databaseIngredients.js and extended against
 * the Curly Check reference list (curlycheck.com, last updated Dec 2025).
 *
 * Spelling variants are NOT listed here. matchIngredients normalises both the
 * label text and these names — sulphate/sulfate, hyphens, spaces and periods
 * all collapse — so one entry covers every spelling of the same word.
 *
 * `aliases` is only for genuinely different names for the same substance, or
 * for spellings normalisation cannot reach (OCR confusing I with l).
 * Non-Latin (Japanese, Korean) forms belong there too.
 */
export const ingredients: Ingredient[] = [
  // sulfates
  { type: "sulfates", name: "alkylbenzene sulfonate", description: "" },
  { type: "sulfates", name: "ammonium cocoyl sulfate", description: "" },
  { type: "sulfates", name: "ammonium laureth sulfate", description: "" },
  { type: "sulfates", name: "ammonium lauryl sulfate", description: "" },
  { type: "sulfates", name: "ammonium xylenesulfonate", description: "" },
  { type: "sulfates", name: "dioctyl sodium sulfosuccinate", description: "" },
  { type: "sulfates", name: "disodium sulfolaurate", description: "" },
  { type: "sulfates", name: "ethyl peg-15 cocamine sulfate", description: "" },
  { type: "sulfates", name: "magnesium lauryl sulfate", description: "" },
  { type: "sulfates", name: "olefin sulfonate", description: "" },
  { type: "sulfates", name: "pluronic and tetronic surfactants", description: "" },
  { type: "sulfates", name: "sodium alkyl sulfate", description: "" },
  { type: "sulfates", name: "sodium alkylbenzene sulfonate", description: "" },
  { type: "sulfates", name: "sodium c 14-18 olefin sulfonate", description: "" },
  { type: "sulfates", name: "sodium c 16-18 olefin sulfonate", description: "" },
  { type: "sulfates", name: "sodium c12-14 olefin sulfonate", description: "" },
  { type: "sulfates", name: "sodium c12-18 alkyl sulfate", description: "" },
  { type: "sulfates", name: "sodium c14-15 olefin sulfonate", description: "" },
  { type: "sulfates", name: "sodium c14-16 olefin sulfonate", description: "" },
  { type: "sulfates", name: "sodium cetearyl sulfate", description: "" },
  { type: "sulfates", name: "sodium coceth sulfate", description: "" },
  { type: "sulfates", name: "sodium cocosulfate", description: "" },
  { type: "sulfates", name: "sodium laureth sulfate", description: "" },
  { type: "sulfates", name: "sodium laureth-40 sulfate", description: "" },
  { type: "sulfates", name: "sodium lauryl ether sulfate", description: "" },
  { type: "sulfates", name: "sodium lauryl glucose carboxylate", description: "" },
  { type: "sulfates", name: "sodium lauryl sulfate", description: "" },
  { type: "sulfates", name: "sodium lauryl sulfoacetate", description: "" },
  { type: "sulfates", name: "sodium methyl 2-sulfolaurate", description: "" },
  { type: "sulfates", name: "sodium myreth sulfate", description: "" },
  { type: "sulfates", name: "sodium olefin sulfonate", description: "" },
  { type: "sulfates", name: "sodium polystyrene sulfate", description: "" },
  { type: "sulfates", name: "sodium polystyrene sulfonate", description: "" },
  { type: "sulfates", name: "sodium trideceth sulfate", description: "" },
  { type: "sulfates", name: "sodium xylenesulfonate", description: "" },
  { type: "sulfates", name: "tea dodecylbenzenesulfonate", description: "" },
  { type: "sulfates", name: "tea lauryl sulfate", description: "" },
  { type: "sulfates", name: "triethanolamine lauryl sulfate", description: "" },
  // silicones
  { type: "silicones", name: "amino bispropyl dimethicone", description: "" },
  { type: "silicones", name: "aminopropyl dimethicone", description: "" },
  { type: "silicones", name: "amodimethicone", description: "" },
  { type: "silicones", name: "behenoxy dimethicone", description: "" },
  { type: "silicones", name: "bis (c13-c15 alkoxy) pg-amodimethicone", description: "" },
  { type: "silicones", name: "bis-amino peg/ppg-41/3 aminoethyl pg-propyl dimethicone", description: "" },
  { type: "silicones", name: "bis-aminoethyl cyclohexene", description: "" },
  { type: "silicones", name: "bis-aminopropyl dimethicone", description: "" },
  { type: "silicones", name: "c24-28 alkyl dimethicone", description: "" },
  { type: "silicones", name: "c30-45 alkyl dimethicone", description: "" },
  { type: "silicones", name: "c30-45 alkyl methicone", description: "" },
  { type: "silicones", name: "cetearyl methicone", description: "" },
  { type: "silicones", name: "cetyl dimethicone", description: "" },
  { type: "silicones", name: "cyclomethicone", description: "" },
  { type: "silicones", name: "cyclopentasiloxane", description: "" },
  { type: "silicones", name: "dimethicone", description: "" },
  { type: "silicones", name: "dimethiconol", description: "" },
  { type: "silicones", name: "hexyl methicone", description: "" },
  { type: "silicones", name: "hydroxypropyl dimethicone", description: "" },
  { type: "silicones", name: "methicone", description: "" },
  { type: "silicones", name: "ofpma-octafluoropentyl methacrylate", description: "" },
  { type: "silicones", name: "phenyl trimethicone", description: "" },
  { type: "silicones", name: "phenylpropyl dimethylsiloxysilicate", description: "" },
  { type: "silicones", name: "polydimethylsiloxane", description: "" },
  { type: "silicones", name: "propyl dimethicone", description: "" },
  { type: "silicones", name: "simethicone", description: "" },
  { type: "silicones", name: "stearamidopropyl dimethicone", description: "" },
  { type: "silicones", name: "stearoxy dimethicone", description: "" },
  { type: "silicones", name: "stearyl dimethicone", description: "" },
  { type: "silicones", name: "stearyl methicone", description: "" },
  { type: "silicones", name: "trimethylsilylamodimethicone", description: "" },
  // alcohols
  { type: "alcohols", name: "alcohol 40", description: "" },
  { type: "alcohols", name: "alcohol denat", description: "" },
  { type: "alcohols", name: "denatured alcohol", description: "" },
  { type: "alcohols", name: "ethanol", description: "" },
  { type: "alcohols", name: "ethyl alcohol", description: "" },
  { type: "alcohols", name: "isopropanol", description: "" },
  { type: "alcohols", name: "isopropyl alcohol", description: "" },
  { type: "alcohols", name: "propanol", description: "" },
  { type: "alcohols", name: "propyl alcohol", description: "" },
  { type: "alcohols", name: "sd alcohol", description: "" },
  { type: "alcohols", name: "sd alcohol 40", description: "" },
  // mineral oils
  { type: "mineral oils", name: "mineral oil", description: "" },
  { type: "mineral oils", name: "paraffin", description: "" },
  {
    type: "mineral oils",
    name: "paraffinum liquidum",
    aliases: ["liquid paraffin", "liquid vaseline"],
    description: "",
  },
  { type: "mineral oils", name: "petrolatum", description: "" },
  { type: "mineral oils", name: "petroleum", description: "" },
  // waxes
  { type: "waxes", name: "beeswax", description: "" },
  { type: "waxes", name: "candelilla wax", description: "" },
  { type: "waxes", name: "carnauba wax", description: "" },
  { type: "waxes", name: "cera microcristallina", description: "" },
  { type: "waxes", name: "ceresine isoparaffin", description: "" },
  { type: "waxes", name: "microcrystalline wax", description: "" },
  { type: "waxes", name: "ozokerite", description: "" },
  { type: "waxes", name: "synthetic wax", description: "" },
  { type: "waxes", name: "wax", description: "" },
  // other drying agents
  { type: "other drying agents", name: "disodium cocoyl glutamate", description: "" },
  { type: "other drying agents", name: "emu oil", description: "" },
  { type: "other drying agents", name: "etas-expandable textured aerospheres", description: "" },
  { type: "other drying agents", name: "sodium carboxylate", description: "" },
  { type: "other drying agents", name: "sodium cocoyl glutamate", description: "" },
  { type: "other drying agents", name: "sodium cocoyl sarcosinate", description: "" },
  { type: "other drying agents", name: "sodium lauroyl sarcosinate", description: "" },
  { type: "other drying agents", name: "sodium lauroyl sarcosine", description: "" },
  {
    type: "other drying agents",
    name: "sodium lauroylmethyl isethionate",
    aliases: ["sodium lauroyl methyl lsethionate", "sodium lauryl methyl isothionate"],
    description: "",
  },
  { type: "other drying agents", name: "sodium lauryl sarcosinate", description: "" },
  { type: "other drying agents", name: "sodium myristoyl sarcosinate", description: "" },
  {
    type: "other drying agents",
    name: "witch hazel",
    aliases: ["hazel"],
    description: "",
  },
];
